"""

Revision ID: bfa6f107ebe2
Revises: 57bc88e06e52
Create Date: 2020-06-24 15:41:42.411127

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfa6f107ebe2"
down_revision = "57bc88e06e52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(), nullable=True),
        sa.Column("answer_html_text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_id"), "quiz", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_id"), table_name="quiz")
    op.drop_table("quiz")
    # ### end Alembic commands ###
